### ISSUE TITLE
ERROR Error encoding stats err="json: unsupported value: NaN"

### ISSUE THREAD

**Issue by Toudahl** [henrygd/beszel#280]
Hi,

One of my agents , running in docker is reporting some errors.

I am not sure how to go about debugging them it, or even fixing it.

```
2024/11/09 17:02:35 INFO Detected root device name=mmcblk0p2
2024/11/09 17:02:35 INFO Detected network interface name=eth0 sent=818916 recv=989631
2024/11/09 17:02:35 INFO Starting SSH server address=:45876
2024/11/09 17:15:14 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:15:14 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:22:35 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:22:35 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:26:56 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:26:56 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:51:05 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:51:05 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:59:25 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 17:59:25 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 18:05:25 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 18:05:25 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/09 18:05:44 ERROR Error encoding stats err=EOF

```

**Comment by henrygd** [comment]
Please add `LOG_LEVEL=debug` to the agent.

What Docker version and device / OS are you using?

**Comment by Toudahl** [comment]
I have enabled debug logging, and I am waiting for the error to reappear.

I am running docker 24.0.6, debian 11 on a rpi3b+.

The agent is version 0.7.2.

Apologies for not including this before.

**Comment by Toudahl** [comment]
```
2024/11/10 22:27:17 DEBUG Getting stats
2024/11/10 22:27:17 DEBUG Temperature sensors="[{\"sensorKey\":\"cpu_thermal\",\"temperature\":62.3,\"sensorHigh\":0,\"sensorCritical\":110}]"
2024/11/10 22:27:17 DEBUG sysinfo data="{Hostname:rpi3bp-01 KernelVersion:6.1.21-v8+ Cores:4 Threads:4 CpuModel:Cortex-A53 Uptime:107421 Cpu:0.33 MemPct:19.53 DiskPct:21.68 Bandwidth:0 AgentVersion:0.7.2}"
2024/11/10 22:27:17 DEBUG System stats data="{Stats:{Cpu:0.33 MaxCpu:0 Mem:0.89 MemUsed:0.17 MemPct:19.53 MemBuffCache:0.49 MemZfsArc:0 Swap:0.1 SwapUsed:0 DiskTotal:14.32 DiskUsed:2.97 DiskPct:21.68 DiskReadPs:0.05 DiskWritePs:0 MaxDiskReadPs:0 MaxDiskWritePs:0 NetworkSent:0 NetworkRecv:0 MaxNetworkSent:0 MaxNetworkRecv:0 Temperatures:map[cpu_thermal:62.3] ExtraFs:map[]} Info:{Hostname:rpi3bp-01 KernelVersion:6.1.21-v8+ Cores:4 Threads:4 CpuModel:Cortex-A53 Uptime:107421 Cpu:0.33 MemPct:19.53 DiskPct:21.68 Bandwidth:0 AgentVersion:0.7.2} Containers:[]}"
2024/11/10 22:27:17 DEBUG Getting stats
2024/11/10 22:27:17 DEBUG Temperature sensors="[{\"sensorKey\":\"cpu_thermal\",\"temperature\":62.3,\"sensorHigh\":0,\"sensorCritical\":110}]"
2024/11/10 22:27:17 DEBUG sysinfo data="{Hostname:rpi3bp-01 KernelVersion:6.1.21-v8+ Cores:4 Threads:4 CpuModel:Cortex-A53 Uptime:107421 Cpu:66.67 MemPct:19.53 DiskPct:21.68 Bandwidth:0.16 AgentVersion:0.7.2}"
2024/11/10 22:27:17 DEBUG System stats data="{Stats:{Cpu:66.67 MaxCpu:0 Mem:0.89 MemUsed:0.17 MemPct:19.53 MemBuffCache:0.49 MemZfsArc:0 Swap:0.1 SwapUsed:0 DiskTotal:14.32 DiskUsed:2.97 DiskPct:21.68 DiskReadPs:0 DiskWritePs:0 MaxDiskReadPs:0 MaxDiskWritePs:0 NetworkSent:0.12 NetworkRecv:0.04 MaxNetworkSent:0 MaxNetworkRecv:0 Temperatures:map[cpu_thermal:62.3] ExtraFs:map[]} Info:{Hostname:rpi3bp-01 KernelVersion:6.1.21-v8+ Cores:4 Threads:4 CpuModel:Cortex-A53 Uptime:107421 Cpu:66.67 MemPct:19.53 DiskPct:21.68 Bandwidth:0.16 AgentVersion:0.7.2} Containers:[]}"
2024/11/10 22:27:18 DEBUG Docker stats data="[0x40000e64d0 0x400006a310]"
2024/11/10 22:27:18 DEBUG Extra filesystems data=map[]
2024/11/10 22:27:18 DEBUG Docker stats data="[0x400006a310 0x40000e64d0]"
2024/11/10 22:27:18 DEBUG Extra filesystems data=map[]
2024/11/10 22:27:18 ERROR Error encoding stats err="json: unsupported value: NaN"
2024/11/10 22:27:18 ERROR Error encoding stats err="json: unsupported value: NaN"

```

**Comment by henrygd** [comment]
Thanks. Is it really logging everything twice or was that just a timing coincidence when you started it up?

Can you please run `docker stats --no-stream` and check if it shows zero values for anything?

I'd recommend upgrading Docker if possible. There's a known bug in 24 that I had to specifically add a workaround for. I don't know if related but it's a good idea to update either way.

**Comment by Toudahl** [comment]
I have now updated to docker 27 - i must have forgotten this rpi when i updated my cluster.
The stats show 0% cpu for beszel, and 0 in network I/O for both containers running on this pi.

I have this in my `/boot/cmdline.txt`
`console=serial0,115200 console=tty1 root=PARTUUID=202246d5-02 rootfstype=ext4 fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`

The logs are showing up twice, both in my syslog server - and when i inspect the logs manually using the docker command.

**Comment by henrygd** [comment]
The issue may be that multiple instances of the hub are requesting metrics from the agent at the same time.

There's no lock coordination between multiple instances atm. Try to make sure only one total instance is running.

**Comment by Toudahl** [comment]
There is only one hub running.
![image](https://github.com/user-attachments/assets/b6dcd107-2904-4b5c-a174-938567e47a0e)

On the hub i am actually seeing this
```
infrastructure_beszel.1.a6vox3xn33lp@rpi4-02    | 2024/11/11 19:10:38 failed to get active systems err context canceled; failed query: SELECT `@@__invalidCollectionModelOrIdentifier`.* FROM `@@__invalidCollectionModelOrIdentifier` WHERE status = 'up'
```

**Comment by henrygd** [comment]
I think this is the same issue as #216 actually. You can also reference this thread about swarm: #17.

It seems to be possible to get working properly, but I haven't set up swarm yet to figure it out.

With swarm, it would be better for the agents to use an internal timer and send stats to the hub, rather than how it's set up currently where the hub requests from the agent. I want to add that option but it's not going to be in the very near future.

I think what's going wrong is that the hub connections are not being handled by the correct nodes, and sometimes one node is being assigned two connections.

Re: failed to get active systems error - that's the first time I've seen someone hit that. Are you using the arm7 image for the hub by any chance? There's an open issue about that image having a problem with the DB (#133) but I haven't been able to troubleshoot it because I don't have an arm7 device.

It may go away if you can figure out a working configuration with the swarm nodes, otherwise you may want to delete the `beszel_data` folder and start over if it continues to happen.

**Comment by Toudahl** [comment]
Sorry for the slow reply time.

Some more details of my system.

I have 1 swarm, with 4 nodes.
These are all running debian 11, and docker 27. The hosts them self are 3 x rpi4 and 1 x rpi4b
This is where the screengrab is from. As you can see it is running 1 hub, and 4 agents using host network.
The hub is connecting to the agents through host ip. So no docker networking involved there.

The original problem i posted about takes places on a separate pi, with details as described.

So aside from the agent running on the rpi3b+, the hub and other agents are running on arm.

Based on this information, I do not think it is likely that the problem is caused by swarm. But if you wish to test it your self, you can easily make a swarm "cluster" with just one node. Perhaps you can trigger the issues there.

**Comment by marb08** [comment]
Sorry to revive an old issue, but I am facing the same one with a slightly different setup.
I have been running both the main service and the agent on the same host smoothly for more than 24 hours. 
Today, I restarted the host for an update, recreated some old containers, and mounted an external disk, but now the agent is failing.

Here are some logs from the agent container:
```
beszel-agent  | 2025/01/02 19:20:40 DEBUG Docker stats data="[0xc000195730 0xc00027d340 0xc0001352d0 0xc000195180 0xc00027c700 0xc000221030 0xc00027c380 0xc0003843f0 0xc00027c9a0 0xc00027cfc0 0xc0003840e0 0xc0003844d0 0xc000221880 0xc000221dc0 0xc000135e30 0xc000135500 0xc0001359d0 0xc00027cd90 0xc000384540 0xc000384f50 0xc0002212d0 0xc0001357a0 0xc0001951f0 0xc000195490 0xc0002d92d0 0xc000221570 0xc000194f50 0xc000221b20 0xc0002d8230 0xc000195500 0xc000195960 0xc000384460 0xc000220af0 0xc000194cb0 0xc00027c0e0]"
beszel-agent  | 2025/01/02 19:20:40 DEBUG Docker stats data="[0xc000195730 0xc00027d340 0xc0001352d0 0xc000195180 0xc00027c700 0xc000221030 0xc00027c380 0xc0003843f0 0xc00027c9a0 0xc00027cfc0 0xc0003840e0 0xc0003844d0 0xc000221880 0xc000221dc0 0xc000135e30 0xc000135500 0xc0001359d0 0xc00027cd90 0xc000384540 0xc000384f50 0xc0002212d0 0xc0001357a0 0xc0001951f0 0xc000195490 0xc0002d92d0 0xc000221570 0xc000194f50 0xc000221b20 0xc0002d8230 0xc000195500 0xc000195960 0xc000384460 0xc000220af0 0xc000194cb0 0xc00027c0e0]"
beszel-agent  | 2025/01/02 19:20:40 DEBUG Extra filesystems data=map[]
beszel-agent  | 2025/01/02 19:20:40 DEBUG Extra filesystems data=map[]
beszel-agent  | 2025/01/02 19:20:40 ERROR Error encoding stats err="json: unsupported value: NaN"
beszel-agent  | 2025/01/02 19:20:40 ERROR Error encoding stats err="json: unsupported value: NaN"
```

I checked and no 0 values are in docker-stats output.

The frontend logs are reporting this error: `Failed to get system stats: EOF`

Here is the docker compose for the agent:
```services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
        #- /mnt/data:/extra-filesystems/sda1:ro
        #- /mnt/nas:/extra-filesystems/sdb1:ro
    environment:
      LOG_LEVEL: debug
      PORT: 45876
      KEY: "ssh-ed25519 PRIVATE-KEY"
```

Not sure what can be wrong, I tried to reboot the host several times and also to restart docker service, but nothing worked.

**Comment by henrygd** [comment]
@marb08 Assuming you're not using swarm, can you please double check that you don't have two instances of the hub running? It looks like the agent is getting two requests at once.

Maybe a situation where config was changed but an orphan container still exists?

I'll add more info to the logs for this error in the next release.

**Comment by marb08** [comment]
First of all thanks for your support and work.
I had time to investigate the problem further: apparently the error occurs only with the hub container up, so it may not be related to how the agent receives statistics or information from the host. As soon as the hub container is pulled up, it presents the error; if the agent runs on its own, it gives no problems.
I attach more logs about it, hope it helps, this is as soon as the hub container spawns:
```
beszel-agent  | 2025/01/03 08:46:31 DEBUG System stats data="{Stats:{Cpu:0 MaxCpu:0 Mem:31.12 MemUsed:4.41 MemPct:14.16 MemBuffCache:10.61 MemZfsArc:0 Swap:8 SwapUsed:0 DiskTotal:467.35 DiskUsed:82.27 DiskPct:18.55 DiskReadPs:0 DiskWritePs:0.05 MaxDiskReadPs:0 MaxDiskWritePs:0 NetworkSent:5.41 NetworkRecv:0 MaxNetworkSent:0 MaxNetworkRecv:0 Temperatures:map[acpitz:30 coretemp_core_0:36 coretemp_core_1:36 coretemp_core_2:37 coretemp_core_3:35 coretemp_package_id_0:37 nvme_composite:31.85 pch_cannonlake:33] ExtraFs:map[] GPUData:map[]} Info:{Hostname:prometheus KernelVersion:5.15.0-130-generic Cores:4 Threads:4 CpuModel:Intel(R) Core(TM) i3-8300T CPU @ 3.20GHz Uptime:49042 Cpu:0 MemPct:14.16 DiskPct:18.55 Bandwidth:5.41 AgentVersion:0.9.0 Podman:false} Containers:[]}"
beszel-agent  | 2025/01/03 08:46:31 DEBUG Retrying failed containers count=1
beszel-agent  | panic: sync: WaitGroup is reused before previous Wait has returned
beszel-agent  |
beszel-agent  | goroutine 267 [running]:
beszel-agent  | sync.(*WaitGroup).Wait(0xc0000140e0?)
beszel-agent  |         /usr/local/go/src/sync/waitgroup.go:120 +0x74
beszel-agent  | beszel/internal/agent.(*dockerManager).getDockerStats(0xc000017860)
beszel-agent  |         /app/internal/agent/docker.go:108 +0x7c5
beszel-agent  | beszel/internal/agent.(*Agent).gatherStats(_)
beszel-agent  |         /app/internal/agent/agent.go:101 +0x21f
beszel-agent  | beszel/internal/agent.(*Agent).handleSession(0xc00003efd0?, {0x8a2808, 0xc0003fc000})
beszel-agent  |         /app/internal/agent/server.go:27 +0x32
beszel-agent  | github.com/gliderlabs/ssh.(*session).handleRequests.func1()
beszel-agent  |         /go/pkg/mod/github.com/gliderlabs/ssh@v0.3.8/session.go:261 +0x27
beszel-agent  | created by github.com/gliderlabs/ssh.(*session).handleRequests in goroutine 266
beszel-agent  |         /go/pkg/mod/github.com/gliderlabs/ssh@v0.3.8/session.go:260 +0x4e7
beszel-agent exited with code 2
```

I tried to see if there were orphaned or similar instances of hub running but found nothing; I am also running the agent (say agentB) on another host and just verified that I actually have problems on that instance as well. Moreover, as soon as the buggy agent (say agentA) to not interfere with the external one (agentB), this one runs smoothly.

After this last discovery I tried running only the agentB alone, pausing the other one from the dashboard. I still run the agentA container and continued like that for about ten/twenty minutes. I then restarted via the dashboard the agentA and it has now been running for about an hour without any problems. The problem seems to have been fixed, but I have no idea what caused it nor solved it.

**Comment by henrygd** [comment]
Interesting, thanks for the detail. I'll look further into it.

**Comment by balgerion** [comment]
#566 - I created an issue because I didn't notice that one. I'm experiencing the same situation on Swarm with the same error.

**Comment by balgerion** [comment]
I just found working woraround you and anyone interested can check it at #566 
Stable for 48h

**Comment by svenvg93** [comment]
No activity on this issue for a long time. Closing it for now. If the issue persists or becomes relevant again, feel free to open a new issue or discussion.
