### ISSUE TITLE
Runtime error on MacOS agent

### ISSUE THREAD

**Issue by daniele2010** [henrygd/beszel#7]
Hi, I'm testing this tool in MacOs (Mac Mini M1), the hub seems to work well, both in docker and as binary.
I cannot make it work the agent, in both ways: in docker I don't see any useful log, below the logs of the error using the agent:

```
⚡ ./beszel-agent
2024/07/25 09:56:59 Using filesystem: /dev/disk3s1s1
2024/07/25 09:56:59 Found network interface: gif0 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: stf0 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: anpi0 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: anpi1 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: en0 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: en4 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: en5 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: en2 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: en3 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: ap1 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: en1 (33259991966 recv, 24598766447 sent)
2024/07/25 09:56:59 Found network interface: awdl0 (0 recv, 470 sent)
2024/07/25 09:56:59 Found network interface: llw0 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: en6 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: bridge0 (0 recv, 0 sent)
2024/07/25 09:56:59 Found network interface: utun0 (0 recv, 320 sent)
2024/07/25 09:56:59 Found network interface: utun1 (0 recv, 260 sent)
2024/07/25 09:56:59 Found network interface: utun2 (0 recv, 200 sent)
2024/07/25 09:56:59 Found network interface: utun3 (0 recv, 80 sent)
2024/07/25 09:56:59 Found network interface: vmenet0 (12368749446 recv, 13318622014 sent)
2024/07/25 09:56:59 Found network interface: bridge100 (12226648160 recv, 26640471544 sent)
2024/07/25 09:56:59 Starting SSH server on port 45876
panic: runtime error: index out of range [0] with length 0

goroutine 25 [running]:
main.getSystemStats()
        /home/runner/work/beszel/beszel/agent/main.go:74 +0x708
main.gatherStats()
        /home/runner/work/beszel/beszel/agent/main.go:255 +0x1c
main.startServer.func1({0x1006f3e58, 0x14000191d40})
        /home/runner/work/beszel/beszel/agent/main.go:271 +0x24
github.com/gliderlabs/ssh.(*session).handleRequests.func1()
        /home/runner/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:261 +0x34
created by github.com/gliderlabs/ssh.(*session).handleRequests in goroutine 24
        /home/runner/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:260 +0x518
```

**Comment by henrygd** [comment]
Thanks for the logs, that's very helpful and I'm sure you're not the only one with the same issue.

I don't have a Mac device myself but going by the logs I think it's an issue with reading the model of the processor.

I'll add a check for this in the next release and loop back here to confirm if it's fixed.

**Comment by henrygd** [comment]
Tried to address this in [0.1.1](https://github.com/henrygd/beszel/releases/tag/v0.1.1).

Good news is that it shouldn't panic again.

Bad news is the error may have been related to getting the CPU utilization. But fingers crossed it's just about getting the model name.

Let know whenever you have a chance to try again. No rush at all.

**Comment by daniele2010** [comment]
It works, just tested with docker! If you need any other test, please ask.

**Comment by henrygd** [comment]
Awesome, thanks!
