### ISSUE TITLE
beszel agent keeps stopping

### ISSUE THREAD

**Issue by volcs0** [henrygd/beszel#96]
Running as a Docker Container in unRAID. Every time I start the agent, it runs for a few hours and then stops. When it's running, it works great. Here is the error log from the agent. Both the agent and the reporting client are up to date.

Anything else I can do to troubleshoot?

```
main.getDockerStats()
        /app/main.go:206 +0x457
main.gatherStats()
        /app/main.go:274 +0x79
main.startServer.func1({0x841738, 0xc0005f00d0})
        /app/main.go:284 +0x25
github.com/gliderlabs/ssh.(*session).handleRequests.func1()
        /go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:261 +0x27
created by github.com/gliderlabs/ssh.(*session).handleRequests in goroutine 744
        /go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:260 +0x4e7

goroutine 799 [IO wait]:
internal/poll.runtime_pollWait(0x15255f33b470, 0x72)
        /usr/local/go/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000294280?, 0xc00019d000?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000294280, {0xc00019d000, 0x1000, 0x1000})
        /usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000294280, {0xc00019d000?, 0x0?, 0xc0005ce8c0?})
        /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00042e018, {0xc00019d000?, 0x0?, 0xc0005cee00?})
        /usr/local/go/src/net/net.go:185 +0x45
net/http.(*persistConn).Read(0xc000420240, {0xc00019d000?, 0xc000444240?, 0xc000595d38?})
        /usr/local/go/src/net/http/transport.go:1977 +0x4a
bufio.(*Reader).fill(0xc000360600)
        /usr/local/go/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc000360600, 0x1)
        /usr/local/go/src/bufio/bufio.go:148 +0x53
net/http.(*persistConn).readLoop(0xc000420240)
        /usr/local/go/src/net/http/transport.go:2141 +0x1b9
created by net/http.(*Transport).dialConn in goroutine 798
        /usr/local/go/src/net/http/transport.go:1799 +0x152f

goroutine 808 [select]:
net/http.(*persistConn).writeLoop(0xc0002ec900)
        /usr/local/go/src/net/http/transport.go:2458 +0xf0
created by net/http.(*Transport).dialConn in goroutine 806
        /usr/local/go/src/net/http/transport.go:1800 +0x1585

goroutine 980 [runnable]:
net/http.(*Transport).dialConn.gowrap3()
        /usr/local/go/src/net/http/transport.go:1800
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1
created by net/http.(*Transport).dialConn in goroutine 978
        /usr/local/go/src/net/http/transport.go:1800 +0x1585

goroutine 963 [select]:
net/http.(*persistConn).roundTrip(0xc0003865a0, 0xc0004d2240)
        /usr/local/go/src/net/http/transport.go:2689 +0x979
net/http.(*Transport).roundTrip(0xa574c0, 0xc0004e25a0)
        /usr/local/go/src/net/http/transport.go:608 +0x79a
net/http.(*Transport).RoundTrip(0xc0004e25a0?, 0x83c1e0?)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x13
net/http.send(0xc0004e2480, {0x83c1e0, 0xa574c0}, {0x1?, 0x4b5513?, 0xa5d560?})
        /usr/local/go/src/net/http/client.go:259 +0x5e4
net/http.(*Client).send(0xa52740, 0xc0004e2480, {0x40e47b?, 0x1?, 0xa5d560?})
        /usr/local/go/src/net/http/client.go:180 +0x98
net/http.(*Client).do(0xa52740, 0xc0004e2480)
        /usr/local/go/src/net/http/client.go:724 +0x8dc
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:590
net/http.(*Client).Get(0xa52740, {0xc0004d40a0?, 0x7dd798?})
        /usr/local/go/src/net/http/client.go:487 +0x5f
main.getContainerStats(0xc000308370)
        /app/main.go:222 +0xc5
main.getDockerStats.func1()
        /app/main.go:192 +0x70
created by main.getDockerStats in goroutine 745
        /app/main.go:190 +0x2e6

goroutine 782 [runnable]:
net/http.(*persistConn).readLoop(0xc000202240)
        /usr/local/go/src/net/http/transport.go:2167 +0x966
created by net/http.(*Transport).dialConn in goroutine 781
        /usr/local/go/src/net/http/transport.go:1799 +0x152f

goroutine 704 [runnable]:
net/http.(*persistConn).readLoop(0xc000202ea0)
        /usr/local/go/src/net/http/transport.go:2167 +0x966
created by net/http.(*Transport).dialConn in goroutine 703
        /usr/local/go/src/net/http/transport.go:1799 +0x152f

goroutine 970 [running]:
main.getDockerStats.func1()
        /app/main.go:195 +0x99
created by main.getDockerStats in goroutine 745
        /app/main.go:190 +0x2e6
```

**Comment by henrygd** [comment]
Possibly related to #19.

What's your output of `docker version`?

**Comment by volcs0** [comment]
> Possibly related to #19.
> 
> What's your output of `docker version`?

Is this what you need? 

`Client:
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:17:06 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:23:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a6
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

**Comment by henrygd** [comment]
Great, thanks!

This strongly points to it being a conflict with very old versions of the Docker API.

You're running the same version (1.41) that the user in the linked issue is using, which was released four or five years ago.

Are you able to update to a more recent version of Docker?

**Comment by henrygd** [comment]
As of 0.1.2 idle connections are purged if a timeout is encountered.

Still recommend updating Docker, but there's an outside shot this could be a fix for old versions.

**Comment by volcs0** [comment]
> As of 0.1.2 idle connections are purged if a timeout is encountered.
> 
> Still recommend updating Docker, but there's an outside shot this could be a fix for old versions.

Been up for 24 hours! 
Thanks for the update.

**Comment by henrygd** [comment]
Good to hear!

I'll close this issue. If it reoccurs, please go to #19 as it seems to be the same issue.
